/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DatingRouteImport } from './routes/dating'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ViralRouteImport } from './routes/viral'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as SmaiIndexRouteImport } from './routes/smai.index'
import { Route as SmaiUsernameRouteImport } from './routes/smai.$username'
import { Route as SpacesIndexRouteImport } from './routes/spaces.index'
import { Route as SpacesSlugRouteImport } from './routes/spaces.$slug'
import { Route as TagTagRouteImport } from './routes/tag.$tag'
import { Route as WaidesIndexRouteImport } from './routes/waides.index'
import { Route as WaidesIdRouteImport } from './routes/waides.$id'
import { Route as SpacesSlugAdminRouteImport } from './routes/spaces.$slug.admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DatingRoute = DatingRouteImport.update({
  id: '/dating',
  path: '/dating',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ViralRoute = ViralRouteImport.update({
  id: '/viral',
  path: '/viral',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MessagesRoute,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SmaiIndexRoute = SmaiIndexRouteImport.update({
  id: '/smai/',
  path: '/smai/',
  getParentRoute: () => rootRouteImport,
} as any)
const SmaiUsernameRoute = SmaiUsernameRouteImport.update({
  id: '/smai/$username',
  path: '/smai/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIndexRoute = SpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSlugRoute = SpacesSlugRouteImport.update({
  id: '/spaces/$slug',
  path: '/spaces/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const WaidesIndexRoute = WaidesIndexRouteImport.update({
  id: '/waides/',
  path: '/waides/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaidesIdRoute = WaidesIdRouteImport.update({
  id: '/waides/$id',
  path: '/waides/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSlugAdminRoute = SpacesSlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => SpacesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/collections': typeof CollectionsRoute
  '/community': typeof CommunityRoute
  '/dating': typeof DatingRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/viral': typeof ViralRoute
  '/messages/$id': typeof MessagesIdRoute
  '/post/$id': typeof PostIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/smai/$username': typeof SmaiUsernameRoute
  '/spaces/$slug': typeof SpacesSlugRouteWithChildren
  '/tag/$tag': typeof TagTagRoute
  '/waides/$id': typeof WaidesIdRoute
  '/smai/': typeof SmaiIndexRoute
  '/spaces/': typeof SpacesIndexRoute
  '/waides/': typeof WaidesIndexRoute
  '/spaces/$slug/admin': typeof SpacesSlugAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/collections': typeof CollectionsRoute
  '/community': typeof CommunityRoute
  '/dating': typeof DatingRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/viral': typeof ViralRoute
  '/messages/$id': typeof MessagesIdRoute
  '/post/$id': typeof PostIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/smai/$username': typeof SmaiUsernameRoute
  '/spaces/$slug': typeof SpacesSlugRouteWithChildren
  '/tag/$tag': typeof TagTagRoute
  '/waides/$id': typeof WaidesIdRoute
  '/smai': typeof SmaiIndexRoute
  '/spaces': typeof SpacesIndexRoute
  '/waides': typeof WaidesIndexRoute
  '/spaces/$slug/admin': typeof SpacesSlugAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/collections': typeof CollectionsRoute
  '/community': typeof CommunityRoute
  '/dating': typeof DatingRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/viral': typeof ViralRoute
  '/messages/$id': typeof MessagesIdRoute
  '/post/$id': typeof PostIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/smai/$username': typeof SmaiUsernameRoute
  '/spaces/$slug': typeof SpacesSlugRouteWithChildren
  '/tag/$tag': typeof TagTagRoute
  '/waides/$id': typeof WaidesIdRoute
  '/smai/': typeof SmaiIndexRoute
  '/spaces/': typeof SpacesIndexRoute
  '/waides/': typeof WaidesIndexRoute
  '/spaces/$slug/admin': typeof SpacesSlugAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/collections'
    | '/community'
    | '/dating'
    | '/login'
    | '/me'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/viral'
    | '/messages/$id'
    | '/post/$id'
    | '/profile/$username'
    | '/smai/$username'
    | '/spaces/$slug'
    | '/tag/$tag'
    | '/waides/$id'
    | '/smai/'
    | '/spaces/'
    | '/waides/'
    | '/spaces/$slug/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/collections'
    | '/community'
    | '/dating'
    | '/login'
    | '/me'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/viral'
    | '/messages/$id'
    | '/post/$id'
    | '/profile/$username'
    | '/smai/$username'
    | '/spaces/$slug'
    | '/tag/$tag'
    | '/waides/$id'
    | '/smai'
    | '/spaces'
    | '/waides'
    | '/spaces/$slug/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bookmarks'
    | '/collections'
    | '/community'
    | '/dating'
    | '/login'
    | '/me'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/viral'
    | '/messages/$id'
    | '/post/$id'
    | '/profile/$username'
    | '/smai/$username'
    | '/spaces/$slug'
    | '/tag/$tag'
    | '/waides/$id'
    | '/smai/'
    | '/spaces/'
    | '/waides/'
    | '/spaces/$slug/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookmarksRoute: typeof BookmarksRoute
  CollectionsRoute: typeof CollectionsRoute
  CommunityRoute: typeof CommunityRoute
  DatingRoute: typeof DatingRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ViralRoute: typeof ViralRoute
  PostIdRoute: typeof PostIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  SmaiUsernameRoute: typeof SmaiUsernameRoute
  SpacesSlugRoute: typeof SpacesSlugRouteWithChildren
  TagTagRoute: typeof TagTagRoute
  WaidesIdRoute: typeof WaidesIdRoute
  SmaiIndexRoute: typeof SmaiIndexRoute
  SpacesIndexRoute: typeof SpacesIndexRoute
  WaidesIndexRoute: typeof WaidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dating': {
      id: '/dating'
      path: '/dating'
      fullPath: '/dating'
      preLoaderRoute: typeof DatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viral': {
      id: '/viral'
      path: '/viral'
      fullPath: '/viral'
      preLoaderRoute: typeof ViralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smai/': {
      id: '/smai/'
      path: '/smai'
      fullPath: '/smai/'
      preLoaderRoute: typeof SmaiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smai/$username': {
      id: '/smai/$username'
      path: '/smai/$username'
      fullPath: '/smai/$username'
      preLoaderRoute: typeof SmaiUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/': {
      id: '/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof SpacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$slug': {
      id: '/spaces/$slug'
      path: '/spaces/$slug'
      fullPath: '/spaces/$slug'
      preLoaderRoute: typeof SpacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waides/': {
      id: '/waides/'
      path: '/waides'
      fullPath: '/waides/'
      preLoaderRoute: typeof WaidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waides/$id': {
      id: '/waides/$id'
      path: '/waides/$id'
      fullPath: '/waides/$id'
      preLoaderRoute: typeof WaidesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$slug/admin': {
      id: '/spaces/$slug/admin'
      path: '/admin'
      fullPath: '/spaces/$slug/admin'
      preLoaderRoute: typeof SpacesSlugAdminRouteImport
      parentRoute: typeof SpacesSlugRoute
    }
  }
}

interface MessagesRouteChildren {
  MessagesIdRoute: typeof MessagesIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesIdRoute: MessagesIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface SpacesSlugRouteChildren {
  SpacesSlugAdminRoute: typeof SpacesSlugAdminRoute
}

const SpacesSlugRouteChildren: SpacesSlugRouteChildren = {
  SpacesSlugAdminRoute: SpacesSlugAdminRoute,
}

const SpacesSlugRouteWithChildren = SpacesSlugRoute._addFileChildren(
  SpacesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookmarksRoute: BookmarksRoute,
  CollectionsRoute: CollectionsRoute,
  CommunityRoute: CommunityRoute,
  DatingRoute: DatingRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ViralRoute: ViralRoute,
  PostIdRoute: PostIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  SmaiUsernameRoute: SmaiUsernameRoute,
  SpacesSlugRoute: SpacesSlugRouteWithChildren,
  TagTagRoute: TagTagRoute,
  WaidesIdRoute: WaidesIdRoute,
  SmaiIndexRoute: SmaiIndexRoute,
  SpacesIndexRoute: SpacesIndexRoute,
  WaidesIndexRoute: WaidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
